services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DMK\MkContentAi\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    DMK\MkContentAi\Backend\EventListener\CustomFileControlsEventListener:
        tags:
            - name: event.listener
              method: handleEvent
              event: TYPO3\CMS\Backend\Form\Event\CustomFileControlsEvent

    DMK\MkContentAi\Backend\EventListener\ModifyFilelistButtonBarEventListener:
        tags:
            - name: event.listener
              method: handleEvent
              event: TYPO3\CMS\Backend\Template\Components\ModifyButtonBarEvent

    DMK\MkContentAi\Backend\EventListener\FileListActionsEventListener:
        public: true
        tags:
            - name: event.listener
              method: handleEvent
              event: TYPO3\CMS\Filelist\Event\ProcessFileListActionsEvent

    DMK\MkContentAi\Backend\EventListener\NewsDatabaseSchemaEventListener:
        tags:
            - name: event.listener
              identifier: 'dmk/mkcontentai/newsDatabaseSchemaEventListener'

    DMK\MkContentAi\Backend\EventListener\NewsRecordEventListener:
        tags:
            - name: event.listener
              identifier: 'dmk/mkcontentai/newsRecordEventListener'

    DMK\MkContentAi\Command\AltTextGenerateCommand:
        tags:
            -
                name: console.command
                command: 'mkcontentai:alt-text-generate'
                description: 'Generate alt texts in specific directory - example: "1:/mkcontentai/openai"'
                schedulable: true

    DMK\MkContentAi\Backend\EventListener\AiAltTextGeneratedEventListener:
        public: true
        tags:
            - name: event.listener
              identifier: 'aiAltTextGenerated'
              event: DMK\MkContentAi\Backend\Event\AiAltTextGeneratedEvent

    DMK\MkContentAi\Backend\EventListener\FileEventListener:
        public: true
        tags:
            - name: event.listener
              identifier: 'beforeSysFileDeleted'
              method: beforeEventDeleted
              event: TYPO3\CMS\Core\Resource\Event\BeforeFileDeletedEvent

    DMK\MkContentAi\Utility\PermissionsUtility:
        calls:
            - method: 'injectContext'
              arguments:
                  $context: '@TYPO3\CMS\Core\Context\Context'
        public: true

    DMK\MkContentAi\Backend\Hooks\ButtonBarHook:
        arguments:
            $permissionsUtility: '@DMK\MkContentAi\Utility\PermissionsUtility'
        public: true

    DMK\MkContentAi\Backend\Hooks\CustomDataHandler:
        arguments:
            $altTextLogsService: '@DMK\MkContentAi\Service\AiAltTextLogsService'
        public: true

    DMK\MkContentAi\Service\SiteLanguageService:
        public: true

    DMK\MkContentAi\Http\Client\AltTextClient:
        public: true

    DMK\MkContentAi\Service\AiAltTextService:
        public: true

    DMK\MkContentAi\Service\AiTranslationPageContentService:
        public: true

    DMK\MkContentAi\Http\Client\Action\AltTextAction:
        public: true

    DMK\MkContentAi\Http\Client\StabilityAiClient:
        calls:
            - method: 'injectStabilityAction'
              arguments:
                  $stabilityAiAction: '@DMK\MkContentAi\Http\Client\Action\StabilityAiAction'
        public: true

    DMK\MkContentAi\Http\Client\SummAiClient:
        calls:
            - method: 'injectSummAiAction'
              arguments:
                  $summAiAction: '@DMK\MkContentAi\Http\Client\Action\SummAiAction'
        public: true

    DMK\MkContentAi\Http\Client\StableDiffusionClient:
        calls:
            - method: 'injectStableDiffusionAction'
              arguments:
                  $stableDiffusionAction: '@DMK\MkContentAi\Http\Client\Action\StableDiffusionAction'
        public: true

    DMK\MkContentAi\Controller\SettingsController:
        calls:
            - method: 'injectAiImageService'
              arguments:
                  $aiImageService: '@DMK\MkContentAi\Service\AiImageService'
        public: true
